version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /
      - /src/*
      - /tests/*
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
